### ISSUE TITLE
cannot import name 'NodeSelector'

### ISSUE THREAD

**Issue by yuewang1402** [Decalogue/chat#16]
Sorry. When I tried to run test_server.py in tests file, it showed an ImportError, which cannot import name 'NodeSelector', from py2neo.
The detailed problem:
Traceback (most recent call last):
  File "chat.py", line 1, in <module>
    from chat import server
  File "/home/medical/Users/Wangyue/chat/chat/server.py", line 12, in <module>
    from .graph import Database
  File "/home/medical/Users/Wangyue/chat/chat/graph.py", line 9, in <module>
    from py2neo import Graph, Node, Relationship, NodeSelector
ImportError: cannot import name 'NodeSelector'

How can I fix that?
Thank you.

**Comment by yuewang1402** [comment]
Just install py2neo v3
pip install git+https://github.com/nigelsmall/py2neo.git#egg=py2neo

**Comment by Decalogue** [comment]
@yuewang1402 Thank you!
