### ISSUE TITLE
关于运行test_client.py

### ISSUE THREAD

**Issue by hjlFrist** [Decalogue/chat#17]
ERROR: test_start (__main__.TestMe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/Anaconda/chat-master/tests/test_client_bank.py", line 13, in test_start
    start(userid=self.userid, key=self.key)
  File "E:\Anaconda\chat-master\chat\client.py", line 121, in start
    print(json.loads(result)['content'])
  File "d:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

这个是啥错误

**Comment by Decalogue** [comment]
您好！这是 json 格式不对引起的错误。可以检查下 test_client.py 运行时具体收发的数据。谢谢！
