### ISSUE TITLE
目标计算机积极拒绝

### ISSUE THREAD

**Issue by David-Lee-1990** [Decalogue/chat#21]
您好，在python中运行  from chat import client ，出现以下错误，该如何调整呢？
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\86132\Anaconda3\lib\site-packages\chat\client.py", line 23, in <module>
    mysock.connect((host, port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。`
感谢

**Comment by Decalogue** [comment]
您好！
    请您查看一下端口是否被占用。或者 server 有没有优先启动。
    谢谢！




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 下午2:37
收件人: "Decalogue/chat"<chat@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Decalogue/chat] 目标计算机积极拒绝 (#21)




您好，在python中运行  from chat import client ，出现以下错误，该如何调整呢？
 Traceback (most recent call last): File "<stdin>", line 1, in <module> File "C:\Users\86132\Anaconda3\lib\site-packages\chat\client.py", line 23, in <module> mysock.connect((host, port)) ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 感谢
